### ISSUE TITLE
Strange routes supposedly source by AS28792

### ISSUE THREAD

**Issue by fischerdouglas** [dashcare/irrexplorer#63]
First, I'm a bit surprised with this new home(dahscare) to irrexplorer.
I hope is for the best! So -> Thanks!

Some friends reported some objets/routes from their ASNs with some routes supposedly originated by AS28792. A Hijack,

I searched on several Looking Glass in the world, and did not find any routes matching with AS28792 as origin as reported by https://irrexplorer.dashcare.nl/asn/AS268385.

![image](https://user-images.githubusercontent.com/7989601/122281129-503ab700-cec0-11eb-8670-0446dc2cd793.png)

This happened at 2021-06-16 16:00(GMT-3)

I Believe that the probable cause is a "not-so-good" sample of DFZ.
Probably a Point of view from AS28792.
And I would bet that this point of view received some synthetic steroids from some route-optimizer.

**Comment by fischerdouglas** [comment]
Another example of same issue:

![image](https://user-images.githubusercontent.com/7989601/122281722-f686bc80-cec0-11eb-93ea-e8deef6fe5e1.png)

**Comment by forkwhilefork** [comment]
Looks like it's using bgp.tools by default: https://github.com/dashcare/irrexplorer/commit/8f6faec073e23f16f1df3cf740afe85ceb6ace6e

I would take this up with the maintainer of bgp.tools.

**Comment by mxsasha** [comment]
I have, but it might take a while to fix. I switched to the NLNOG RING feed for now.

**Comment by benjojo** [comment]
(bgp.tools maintainer here) I'll check in with this, Might take a while to go backwards on data imports
