### ISSUE TITLE
Outdated DFZ/RPKI data?

### ISSUE THREAD

**Issue by Peter0x48** [dashcare/irrexplorer#68]
Hi,

For me it looks like the DFZ and RPKI data is outdated:

- New route of an AS known to me is not displayed, instead the old one is displayed
- Another AS I know had only a /29 IPv6 ROA and now created two /36 (from this /29) IRR Route and ROA entries. Error is "RPKI invalid route objects found" so it looks like IRR is updated, but RPKI not

"http://lg01.infra.ring.nlnog.net/table.txt" as referenced in the README as "BGP_SOURCE" is "404 Not Found".

Thanks!

**Comment by mxsasha** [comment]
The RPKI issue was fixed last week, this was a local IRRd misconfiguration on the instance. The DFZ data feed also has some issues, ecdf14420dc5327dc4e53ff752849d57b836090a updates it to the new bgp.tools feed. So this should all be fixed now.
