### ISSUE TITLE
Hosted version @ https://irrexplorer.dashcare.nl/ not working

### ISSUE THREAD

**Issue by BrendanHalley** [dashcare/irrexplorer#73]
Hello,

For a few days now the hosted version of this script at https://irrexplorer.dashcare.nl/ has not been working.

After entering a prefix a blank page appears.

![image](https://user-images.githubusercontent.com/4285050/127250166-39eab014-52e0-4f24-9dea-7d3bdf9b1b01.png)

This seems to be caused by the request to the prefix API endpoint returning a 500 error.

![image](https://user-images.githubusercontent.com/4285050/127250240-79001e41-e00c-4a85-9669-a478bc126d4d.png)

Is the hosted version of this script not a production system but instead a dev environment?

**Comment by mxsasha** [comment]
Thanks for reporting, I fixed it a few hours ago :)
